name: Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        # Use the same version as defined for the testing environment: https://github.com/Cockatrice/Magic-Spoiler/blob/master/tox.ini#L5
        uses: actions/setup-python@v2
          with:
            python-version: 3.7

      - name: Install requirements using pip
        shell: bash
        env:
          CFLAGS: '-O0'
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install --requirement requirements.txt
          python3 -m pip install --upgrade tox

      - name: Run tests using Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
